### ISSUE TITLE
Add zip file decompression

### ISSUE THREAD

**Issue by pyrox0** [xermicus/blindspot#3]
I am trying to install Syncthing, and their CI packages builds as .zip files. Could you add compatibility for zip files in this?

**Comment by xermicus** [comment]
Yes! Async support has unfortunately not yet landed in the zip crate I'd like to use. But this new [PR](https://github.com/zip-rs/zip/pull/204) looks quite promising so I hope to be adding support for zip files soon (implementing the async reader interface on my own would be possible but I don't have time for that right now).

**Comment by arickconley** [comment]
What's the latest on this? Tried installing `exa`, but Blindspot gets to the point of `"Choose a file from Tar archive"` and then it doesn't list anything.
